I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/script_3.rpy", line 29, in script
    jump rute_4b
ScriptError: could not find label 'rute_4b'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/script_3.rpy", line 29, in script
    jump rute_4b
  File "/home/hernowo/Data_Hernowo/Program/Linux/renpy-6.99.13-sdk/renpy/ast.py", line 1552, in execute
    rv = renpy.game.script.lookup(target)
  File "/home/hernowo/Data_Hernowo/Program/Linux/renpy-6.99.13-sdk/renpy/script.py", line 861, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'rute_4b'.

Linux-4.8.0-53-generic-x86_64-with-debian-stretch-sid
Ren'Py 6.99.13.2919
Cengoh Software 1.0
